In [6]:
import numpy as np 

In [7]:
# np.array() creates a numpy list from an existing list or a new list can be entered within the object 

a = np.array([[[1,2],[3,2]],[[3,5],[4,7]],[[1,4],[2,9]]]) # this is a 3-D array 
a2 = np.array([[2,4],[6,7],[9,2]]) # this is a 2-D array
a3 = np.array([1,2,3,4]) # this is a 1-D array

In [8]:
# np.linspace() creates an evenly spaced array , in this case it creates an array having 5 elements from 1-3 
i = np.linspace(1,3,5)
print(i)

[1.  1.5 2.  2.5 3. ]


In [9]:
# np.arrange() creates a 1-D array , in this case it creates an array  of digits from 1 to 10 with a step of 0.5 
b = np.arange(1,10,0.5)
print(b)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [10]:
# np.diag() creates a diagonal matrix with the inputs being the diagonal elements and all other elements being zero 
""" It also has another function , i.e , when a 2-D or higher dimensional array is given as input 
it gives a 1-D array containing diagonal elemets as output """
c = np.diag(a2)
c2 = np.diag([1,2,3])
print(c,c2)

[2 7] [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [11]:
# np.zeros() creates a zero matrix , in this case it creates one zero matrix having two rows and 3 columns 
d = np.zeros((1,2,3))
print(d)

[[[0. 0. 0.]
  [0. 0. 0.]]]


In [12]:
# np.eye creates an identity matrix whose order is the input 
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# np.ones() creates a matrix with all elements being 1 , in this case it creates 1 matrix having 3 rows and 3 columns
f = np.ones((1,3,3))
print(f)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [14]:

# np.random.randint() creates random integers , in this case it creates 5 random numbers from 1 to 10
g = np.random.randint(1,10,5)
print(g)


[9 2 3 5 4]


In [15]:

# The view object duplicates an array , but it is not a true copy of the array as any changes made into duplicate will affect the original array 
e2 = e.view()
print(e2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# np.copy() copies an array , it is a true copy 
f2 = np.copy(f)
print(f2)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [17]:
# np.vstack() takes a 2-D or higher dimensional array and vertically stacks the elements  
h1 = np.vstack(a)
print(h1)

[[1 2]
 [3 2]
 [3 5]
 [4 7]
 [1 4]
 [2 9]]


In [18]:

# np.hstack() takes a 2-D or higher dimensional array and horizontally stacks the elements 
h2 = np.hstack(e)
print(h2)

[1. 0. 0. 0. 1. 0. 0. 0. 1.]


In [19]:
# np.shape() returns the shape of array ( order of the matrix)
j = np.shape(e)
print(j)

(3, 3)


In [25]:
#  np.reshape() takes all the elements into one set and creates a matrix of desired shape or order m*n ( in this case-(2,3) ) this does not work if number of elements is not equal to m*n

x = np.array([[1,2],[3,4],[5,6]])
y = np.reshape(x,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


In [48]:
# np.concatenate() joins arrays 
m = np.concatenate((a2,x))
print(m)

[[2 4]
 [6 7]
 [1 2]
 [3 4]
 [5 6]]


In [26]:
# np.ravel() collapses N-dimesnional array into a 1-D array 
k = np.ravel(x)
print(k)

[1 2 3 4 5 6]


In [37]:
# Array slicing for 1-D arrays : It is method of extracting a part of an array to be used in another array or function 
# It can be depicted as [start:end:step] where start and end are the indices of the elements 
# If start or end values are not specified , it is considered 0 whereas step is considered 1 if unspecified
z = np.array([1,2,3,4,5,6,7,8,9,10])
z1 = z[1:10:2]
print(z1)
#if negative values are used it means the index is counted from the left

[ 2  4  6  8 10]


In [39]:
# Array slicing for 2-D arrays : 
# it is depicted as [x , start:end:step] where x is the index number for the array which is to be sliced
l = x[2,0:2:1]
print(l)

[5 6]


In [41]:
# Iterating elements : It means running through every element in the array 
# Iterating is required for many functions , so the np.nditer() method is used  
for v in np.nditer(x):
    print(v)

1
2
3
4
5
6


In [50]:
# np.array_split() into the number of parts we want the array to split into 
w = np.array_split(m , 3)
print(w)

[array([[2, 4],
       [6, 7]]), array([[1, 2],
       [3, 4]]), array([[5, 6]])]


In [57]:
# np.where() method allows you to search the array according to the condition we input 
# in this case , I want all even numbers 
u = np.where(v == 2)
print(u)

(array([], dtype=int64),)


C:\Users\sohan\AppData\Local\Temp\ipykernel_3416\3888106429.py:3: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
  u = np.where(v == 2)


In [59]:
# np.sort() allows us to re-arrange the elements in ascending order 

q = np.array([11,23,4,53,6,77,54,37,0,12])
s = np.sort(q)
print(s)

[ 0  4  6 11 12 23 37 53 54 77]


In [60]:
# np.repeat() method allows us to repeat the elements of an array the number of times we want to 
t = np.repeat(m,3)
print(t)

[2 2 2 4 4 4 6 6 6 7 7 7 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6]
